export type HttpMethod = 'get' | 'post' | 'put' | 'patch' | 'delete'

export type OpKind = 'read' | 'write' | 'batch'

export interface OpMetadata {
  name: string
  method: HttpMethod
  pathSuffix: string
  configKey: string
  kind: OpKind
  coreName: string
  successStatus: number
  requiredBodyFields: readonly string[]
  supportsPostRead: boolean
  supportsProjection: boolean
  excludeFromEnableAll: boolean
  writeStrategyAffected: boolean
  errors: readonly number[]
  responseDesc: string
  transport: string
  argsSchema: readonly string[]
  requiredArgs: readonly string[]
  notes: string
}

export const OPERATION_METADATA: readonly OpMetadata[] = [
  {
    name: 'findMany',
    method: 'get',
    pathSuffix: '',
    configKey: 'findMany',
    kind: 'read',
    coreName: 'findMany',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 500, 501, 503],
    responseDesc: 'Array of records',
    transport: 'GET query params',
    argsSchema: [
      'where',
      'select',
      'include',
      'omit',
      'orderBy',
      'cursor',
      'take',
      'skip',
      'distinct',
    ],
    requiredArgs: [],
    notes: 'Pagination limits may apply when configured.',
  },
  {
    name: 'findUnique',
    method: 'get',
    pathSuffix: '/unique',
    configKey: 'findUnique',
    kind: 'read',
    coreName: 'findUnique',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 500, 501, 503],
    responseDesc: 'Single record or null',
    transport: 'GET query params',
    argsSchema: ['where', 'select', 'include', 'omit'],
    requiredArgs: ['where'],
    notes: 'Returns null (not 404) when no record matches.',
  },
  {
    name: 'findUniqueOrThrow',
    method: 'get',
    pathSuffix: '/unique/strict',
    configKey: 'findUniqueOrThrow',
    kind: 'read',
    coreName: 'findUniqueOrThrow',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 404, 500, 501, 503],
    responseDesc: 'Single record',
    transport: 'GET query params',
    argsSchema: ['where', 'select', 'include', 'omit'],
    requiredArgs: ['where'],
    notes: 'Returns 404 when no record matches.',
  },
  {
    name: 'findFirst',
    method: 'get',
    pathSuffix: '/first',
    configKey: 'findFirst',
    kind: 'read',
    coreName: 'findFirst',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 500, 501, 503],
    responseDesc: 'Single record or null',
    transport: 'GET query params',
    argsSchema: [
      'where',
      'select',
      'include',
      'omit',
      'orderBy',
      'cursor',
      'take',
      'skip',
      'distinct',
    ],
    requiredArgs: [],
    notes: 'Returns null (not 404) when no record matches.',
  },
  {
    name: 'findFirstOrThrow',
    method: 'get',
    pathSuffix: '/first/strict',
    configKey: 'findFirstOrThrow',
    kind: 'read',
    coreName: 'findFirstOrThrow',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 404, 500, 501, 503],
    responseDesc: 'Single record',
    transport: 'GET query params',
    argsSchema: [
      'where',
      'select',
      'include',
      'omit',
      'orderBy',
      'cursor',
      'take',
      'skip',
      'distinct',
    ],
    requiredArgs: [],
    notes: 'Returns 404 when no record matches.',
  },
  {
    name: 'findManyPaginated',
    method: 'get',
    pathSuffix: '/paginated',
    configKey: 'findManyPaginated',
    kind: 'read',
    coreName: 'findManyPaginated',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc: '{ data: Record[], total: number, hasMore: boolean }',
    transport: 'GET query params',
    argsSchema: [
      'where',
      'select',
      'include',
      'omit',
      'orderBy',
      'cursor',
      'take',
      'skip',
      'distinct',
    ],
    requiredArgs: [],
    notes:
      'Wraps findMany with total count. hasMore is reliable for forward offset pagination (skip + take) only. Distinct count over 100k falls back to approximate total. 409 possible on transaction conflict.',
  },
  {
    name: 'count',
    method: 'get',
    pathSuffix: '/count',
    configKey: 'count',
    kind: 'read',
    coreName: 'count',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: false,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 500, 501, 503],
    responseDesc: 'Integer, or per-field count object when select is provided',
    transport: 'GET query params',
    argsSchema: ['where', 'orderBy', 'cursor', 'take', 'skip', 'select'],
    requiredArgs: [],
    notes:
      'select here means count-specific field selection, not record field selection.',
  },
  {
    name: 'aggregate',
    method: 'get',
    pathSuffix: '/aggregate',
    configKey: 'aggregate',
    kind: 'read',
    coreName: 'aggregate',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: false,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 500, 501, 503],
    responseDesc:
      'Object with requested aggregate fields (_count, _avg, _sum, _min, _max)',
    transport: 'GET query params',
    argsSchema: [
      'where',
      'orderBy',
      'cursor',
      'take',
      'skip',
      '_count',
      '_avg',
      '_sum',
      '_min',
      '_max',
    ],
    requiredArgs: [],
    notes: '_avg, _sum only apply to numeric fields.',
  },
  {
    name: 'groupBy',
    method: 'get',
    pathSuffix: '/groupby',
    configKey: 'groupBy',
    kind: 'read',
    coreName: 'groupBy',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: true,
    supportsProjection: false,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 500, 501, 503],
    responseDesc:
      'Array of objects, each with grouped field values and requested aggregates',
    transport: 'GET query params',
    argsSchema: [
      'by',
      'where',
      'orderBy',
      'having',
      'take',
      'skip',
      '_count',
      '_avg',
      '_sum',
      '_min',
      '_max',
    ],
    requiredArgs: ['by'],
    notes:
      'by is a JSON-encoded array of scalar field names. orderBy is required when using skip or take. Response contains only the by-fields plus requested aggregates.',
  },
  {
    name: 'create',
    method: 'post',
    pathSuffix: '',
    configKey: 'create',
    kind: 'write',
    coreName: 'create',
    successStatus: 201,
    requiredBodyFields: ['data'],
    supportsPostRead: false,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc: 'Created record (201)',
    transport: 'POST JSON body',
    argsSchema: ['data', 'select', 'include', 'omit'],
    requiredArgs: ['data'],
    notes: '409 on unique constraint violation.',
  },
  {
    name: 'createMany',
    method: 'post',
    pathSuffix: '/many',
    configKey: 'createMany',
    kind: 'batch',
    coreName: 'createMany',
    successStatus: 201,
    requiredBodyFields: ['data'],
    supportsPostRead: false,
    supportsProjection: false,
    excludeFromEnableAll: false,
    writeStrategyAffected: true,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc: '{ count: number } (201)',
    transport: 'POST JSON body',
    argsSchema: ['data', 'skipDuplicates'],
    requiredArgs: ['data'],
    notes:
      'data is an array of scalar-only inputs. Nested relation writes are not supported. skipDuplicates silently ignores conflicts (not supported on all providers).',
  },
  {
    name: 'createManyAndReturn',
    method: 'post',
    pathSuffix: '/many/return',
    configKey: 'createManyAndReturn',
    kind: 'batch',
    coreName: 'createManyAndReturn',
    successStatus: 201,
    requiredBodyFields: ['data'],
    supportsPostRead: false,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc: 'Array of created records (201)',
    transport: 'POST JSON body',
    argsSchema: ['data', 'skipDuplicates', 'select', 'include', 'omit'],
    requiredArgs: ['data'],
    notes:
      'Like createMany but returns created records. data items are scalar-only. Requires Prisma 5.14.0+, PostgreSQL/CockroachDB/SQLite only. The order of returned records is not guaranteed.',
  },
  {
    name: 'update',
    method: 'put',
    pathSuffix: '',
    configKey: 'update',
    kind: 'write',
    coreName: 'update',
    successStatus: 200,
    requiredBodyFields: ['where', 'data'],
    supportsPostRead: false,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 404, 409, 500, 501, 503],
    responseDesc: 'Updated record',
    transport: 'PUT JSON body',
    argsSchema: ['where', 'data', 'select', 'include', 'omit'],
    requiredArgs: ['where', 'data'],
    notes:
      '404 when the record to update is not found. 409 on unique constraint violation or transaction conflict.',
  },
  {
    name: 'updateMany',
    method: 'put',
    pathSuffix: '/many',
    configKey: 'updateMany',
    kind: 'batch',
    coreName: 'updateMany',
    successStatus: 200,
    requiredBodyFields: ['where', 'data'],
    supportsPostRead: false,
    supportsProjection: false,
    excludeFromEnableAll: false,
    writeStrategyAffected: true,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc: '{ count: number }',
    transport: 'PUT JSON body',
    argsSchema: ['where', 'data'],
    requiredArgs: ['where', 'data'],
    notes:
      'Updates all matching records with scalar-only data. Nested relation writes are not supported. Returns count, not records. 409 on unique constraint violation.',
  },
  {
    name: 'updateManyAndReturn',
    method: 'put',
    pathSuffix: '/many/return',
    configKey: 'updateManyAndReturn',
    kind: 'batch',
    coreName: 'updateManyAndReturn',
    successStatus: 200,
    requiredBodyFields: ['where', 'data'],
    supportsPostRead: false,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc: 'Array of updated records',
    transport: 'PUT JSON body',
    argsSchema: ['where', 'data', 'select', 'include', 'omit'],
    requiredArgs: ['where', 'data'],
    notes:
      'Like updateMany but returns updated records. data is scalar-only. Requires Prisma 6.2.0+, PostgreSQL/CockroachDB/SQLite only. 409 on unique constraint violation.',
  },
  {
    name: 'upsert',
    method: 'patch',
    pathSuffix: '',
    configKey: 'upsert',
    kind: 'write',
    coreName: 'upsert',
    successStatus: 200,
    requiredBodyFields: ['where', 'create', 'update'],
    supportsPostRead: false,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc: 'Created or updated record',
    transport: 'PATCH JSON body',
    argsSchema: ['where', 'create', 'update', 'select', 'include', 'omit'],
    requiredArgs: ['where', 'create', 'update'],
    notes: 'Creates if not found, updates if found.',
  },
  {
    name: 'delete',
    method: 'delete',
    pathSuffix: '',
    configKey: 'delete',
    kind: 'write',
    coreName: 'deleteUnique',
    successStatus: 200,
    requiredBodyFields: ['where'],
    supportsPostRead: false,
    supportsProjection: true,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 404, 500, 501, 503],
    responseDesc: 'Deleted record',
    transport: 'DELETE JSON body',
    argsSchema: ['where', 'select', 'include', 'omit'],
    requiredArgs: ['where'],
    notes: '404 when the record to delete is not found.',
  },
  {
    name: 'deleteMany',
    method: 'delete',
    pathSuffix: '/many',
    configKey: 'deleteMany',
    kind: 'batch',
    coreName: 'deleteMany',
    successStatus: 200,
    requiredBodyFields: ['where'],
    supportsPostRead: false,
    supportsProjection: false,
    excludeFromEnableAll: false,
    writeStrategyAffected: false,
    errors: [400, 403, 500, 501, 503],
    responseDesc: '{ count: number }',
    transport: 'DELETE JSON body',
    argsSchema: ['where'],
    requiredArgs: ['where'],
    notes: 'Deletes all matching records. Returns count, not records.',
  },
  {
    name: 'updateEach',
    method: 'post',
    pathSuffix: '/each',
    configKey: 'updateEach',
    kind: 'batch',
    coreName: 'updateEach',
    successStatus: 200,
    requiredBodyFields: [],
    supportsPostRead: false,
    supportsProjection: false,
    excludeFromEnableAll: true,
    writeStrategyAffected: false,
    errors: [400, 403, 409, 500, 501, 503],
    responseDesc:
      'Non-atomic: per-row { status, data } / { status, error } array. Atomic: array of records.',
    transport: 'POST JSON body (array)',
    argsSchema: [],
    requiredArgs: ['array of { where, data }'],
    notes:
      'Internal batch endpoint. Bypasses guard shapes. Not enabled by enableAll. Non-atomic max 1000 items, atomic max 100 items. Header x-batch-atomic:true switches to transactional mode.',
  },
]

export const OPERATION_BY_NAME: Record<string, OpMetadata> = Object.fromEntries(
  OPERATION_METADATA.map((m) => [m.name, m]),
)

export const READ_OPERATIONS: readonly OpMetadata[] = OPERATION_METADATA.filter(
  (m) => m.kind === 'read',
)

export const WRITE_OPERATIONS: readonly OpMetadata[] =
  OPERATION_METADATA.filter((m) => m.kind === 'write' || m.kind === 'batch')

export const READ_OPERATION_NAMES = new Set(READ_OPERATIONS.map((m) => m.name))

export interface OperationDef {
  name: string
  method: HttpMethod
  pathSuffix: string
  configKey: string
  excludeFromEnableAll?: boolean
}

export const OPERATION_DEFS: OperationDef[] = OPERATION_METADATA.map((m) => ({
  name: m.name,
  method: m.method,
  pathSuffix: m.pathSuffix,
  configKey: m.configKey,
  excludeFromEnableAll: m.excludeFromEnableAll || undefined,
}))

export function getPostReadPathSuffix(opName: string): string {
  if (opName === 'findMany') return '/read'
  const meta = OPERATION_BY_NAME[opName]
  return meta ? meta.pathSuffix : ''
}

export function isOperationEnabled(
  config: Record<string, any>,
  def: OperationDef | OpMetadata,
): boolean {
  if (config[def.configKey] === false) return false
  if (def.excludeFromEnableAll) return !!config[def.configKey]
  return !!(config.enableAll || config[def.configKey])
}
