import { describe, it, expect, afterAll } from 'vitest'
import fastify, { type FastifyInstance } from 'fastify'
import { Client } from '@modelcontextprotocol/client'
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/client'
import { McpServer, type AuthInfo } from '@modelcontextprotocol/server'
import {
  registerMcpTools,
  createMcpReadTool,
} from '../../../src/copy/mcpRuntime'
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { generateMcpMount } from '../../../src/generators/generateMcpApp'

/**
 * A real Fastify + MCP round trip through the EMITTED mount glue
 * (mcpMount.ts, generated by generateMcpMount and transformed in place by
 * vitest like every other emitted artifact), proving reply.hijack(): without
 * it Fastify's own reply lifecycle corrupts the Streamable HTTP response
 * after the Node handler returns.
 */

const authInfo: AuthInfo = {
  token: 'fastify-token',
  clientId: 'tenant-a',
  scopes: ['mcp'],
  expiresAt: Date.now() + 3_600_000,
} as AuthInfo

let dirPromise: Promise<string> | undefined
const servers: FastifyInstance[] = []
afterAll(async () => {
  await Promise.all(servers.map((s) => s.close()))
  const { readdir } = await import('node:fs/promises')
  const genRoot = resolve(__dirname, '../../..')
  for (const entry of await readdir(genRoot).catch(() => [])) {
    if (entry.startsWith('.mcp-fastify-')) {
      await rm(resolve(genRoot, entry), { recursive: true, force: true })
    }
  }
})

async function emittedMount(): Promise<{
  createMcpFastifyHandler: (
    get: (authInfo: AuthInfo) => McpServer,
  ) => (
    request: { raw: unknown; body: unknown },
    reply: { hijack: () => void; raw: unknown },
  ) => Promise<void>
}> {
  dirPromise ??= (async () => {
    const dir = await mkdtemp(resolve(__dirname, '../../../.mcp-fastify-'))
    await mkdir(dir, { recursive: true })
    await writeFile(
      resolve(dir, 'mcpMount.ts'),
      generateMcpMount({ target: 'fastify', importStyle: 'none' }),
      'utf8',
    )
    return dir
  })()
  const dir = await dirPromise
  return (await import(resolve(dir, 'mcpMount.ts'))) as never
}

describe('MCP over Fastify with the emitted mount glue', () => {
  it('lists and calls tools through /mcp with reply.hijack()', async () => {
    const { createMcpFastifyHandler } = await emittedMount()

    const delegate = {
      findMany: async (query: unknown) => {
        void query
        return [{ id: 'u1', email: 'a@b.c' }]
      },
    }
    const app = fastify()
    app.addHook('onRequest', async (request) => {
      ;(request.raw as unknown as { auth: AuthInfo }).auth = authInfo
    })
    app.all(
      '/mcp',
      createMcpFastifyHandler((auth) => {
        const server = new McpServer({ name: 'fastify-api', version: '1.0.0' })
        registerMcpTools(server, {
          prisma: { user: delegate },
          resolveCaller: (a) =>
            a?.clientId === 'tenant-a' ? 'tenant-a' : undefined,
          authorize: () => undefined,
          defaultLimit: 5,
          maxLimit: 50,
          maxResultBytes: 1_000_000,
          authInfo: auth,
          tools: [
            createMcpReadTool({
              model: 'User',
              operation: 'findMany',
              config: {
                findMany: {
                  variants: { 'tenant-a': { shape: { take: 50 } } },
                },
              },
              core: async (ctx) => {
                void ctx.guardShape
                void ctx.guardCaller
                return delegate.findMany(ctx.parsedQuery)
              },
              fields: [
                {
                  name: 'id',
                  kind: 'scalar',
                  type: 'String',
                  isList: false,
                  isRequired: true,
                },
                {
                  name: 'email',
                  kind: 'scalar',
                  type: 'String',
                  isList: false,
                  isRequired: true,
                },
              ],
              enums: new Map(),
              modelIndex: new Map(),
            }),
          ],
        })
        return server
      }),
    )
    await app.ready()
    servers.push(app)
    const address = await app.listen({ port: 0, host: '127.0.0.1' })

    const client = new Client({ name: 'fastify-client', version: '1.0.0' })
    const transport = new StreamableHTTPClientTransport(
      new URL(`${address}/mcp`),
    )
    await client.connect(transport)
    try {
      const listed = await client.listTools()
      expect(listed.tools.map((t) => t.name)).toEqual(['user_find_many'])

      const called = await client.callTool({
        name: 'user_find_many',
        arguments: { take: 10 },
      })
      expect(called.isError).toBeFalsy()
      const block = (
        called.content as Array<{ type: string; text?: string }>
      )[0]
      expect(JSON.parse(block?.text ?? '[]')).toEqual([
        { id: 'u1', email: 'a@b.c' },
      ])
    } finally {
      await client.close()
    }
  }, 60_000)
})
