import { GeneratorOptions } from '@prisma/generator-helper'
import * as fs from 'fs'
import * as path from 'path'
import { Target } from '../constants'
import { ImportStyle } from './resolveImportStyle'
import { importExt } from './importExt'

const SHARED_FILES = [
  'parseQueryParams.ts',
  'buildModelOpenApi.ts',
  'operationDefinitions.ts',
  'misc.ts',
  'routeConfig.ts',
  'docsRenderer.ts',
  'operationRuntime.ts',
]

const EXPRESS_ONLY_FILES = [
  'autoIncludePlanner.ts',
  'autoIncludeRuntime.ts',
  'materializedRouter.ts',
]

interface CopyFileOptions {
  required?: boolean
  importRewrites?: Array<{ from: string; to: string }>
  destFilename?: string
}

function resolveTemplateDir(subpath: string): string {
  const fromSrc = path.join(__dirname, '..', '..', 'src', subpath)
  if (fs.existsSync(fromSrc)) return fromSrc
  const fromDist = path.join(__dirname, '..', subpath)
  if (fs.existsSync(fromDist)) return fromDist
  throw new Error(
    'Template directory "' + subpath + '" not found.\n  Searched:\n    ' +
    fromSrc + '\n    ' + fromDist + '\n  __dirname: ' + __dirname,
  )
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

const RELATIVE_IMPORT_RE =
  /(\b(?:import|export)\b[^'";]*?\bfrom\s+|\bimport\s+|\bimport\s*\(\s*)(['"])(\.{1,2}\/[^'"\n]+)\2/g

const SKIP_EXTENSION_RE = /\.(m?[jt]sx?|json|css|svg|png|jpe?g|gif|webp|wasm)$/i

function applyExtension(content: string, style: ImportStyle): string {
  if (style === 'none') return content
  const ext = importExt(style)
  if (!ext) return content
  return content.replace(RELATIVE_IMPORT_RE, (_match, prefix, quote, spec) => {
    if (SKIP_EXTENSION_RE.test(spec)) return prefix + quote + spec + quote
    return prefix + quote + spec + ext + quote
  })
}

function copyFileSync(
  srcDir: string,
  destDir: string,
  filename: string,
  importStyle: ImportStyle,
  options?: CopyFileOptions,
): string | null {
  const srcPath = path.join(srcDir, filename)
  const destFilename = options?.destFilename || filename
  const destPath = path.join(destDir, destFilename)

  if (!fs.existsSync(srcPath)) {
    if (options?.required) return 'Required file not found: ' + srcPath
    return null
  }

  const destDirPath = path.dirname(destPath)
  if (!fs.existsSync(destDirPath)) fs.mkdirSync(destDirPath, { recursive: true })

  let content = fs.readFileSync(srcPath, 'utf-8')

  if (options?.importRewrites) {
    for (const rewrite of options.importRewrites) {
      if (rewrite.from === rewrite.to) continue
      content = content.replace(
        new RegExp('from [\'"]' + escapeRegex(rewrite.from) + '[\'"]', 'g'),
        "from '" + rewrite.to + "'",
      )
    }
  }

  const header =
    '/**\n' +
    ' * Auto-generated by prisma-generator-express\n' +
    ' * DO NOT EDIT MANUALLY\n' +
    ' */\n\n'

  if (!content.startsWith('/**')) content = header + content

  content = applyExtension(content, importStyle)

  fs.writeFileSync(destPath, content)
  return null
}

export async function copyFiles(
  options: GeneratorOptions,
  target: Target,
  importStyle: ImportStyle,
): Promise<void> {
  const outputPath = options.generator.output?.value
  if (!outputPath) return

  const copyBase = resolveTemplateDir('copy')
  const errors: string[] = []

  console.log('  Copying utility files to: ' + outputPath + ' (target: ' + target + ')')

  for (const file of SHARED_FILES) {
    const err = copyFileSync(copyBase, outputPath, file, importStyle, { required: true })
    if (err) errors.push(err)
  }

  if (target === 'express') {
    for (const file of EXPRESS_ONLY_FILES) {
      const err = copyFileSync(copyBase, outputPath, file, importStyle, { required: true })
      if (err) errors.push(err)
    }
  }

  const targetConfigFile = 'routeConfig.' + target + '.ts'
  const err = copyFileSync(copyBase, outputPath, targetConfigFile, importStyle, {
    required: true,
    destFilename: 'routeConfig.target.ts',
  })
  if (err) errors.push(err)

  const clientDir = path.join(outputPath, 'client')
  if (!fs.existsSync(clientDir)) fs.mkdirSync(clientDir, { recursive: true })

  const clientSrcDir = resolveTemplateDir('client')
  const clientErr = copyFileSync(clientSrcDir, clientDir, 'encodeQueryParams.ts', importStyle, {
    required: true,
    importRewrites: [{ from: '../copy/misc', to: '../misc' }],
  })
  if (clientErr) errors.push(clientErr)

  if (errors.length > 0) {
    throw new Error(
      'Failed to copy ' + errors.length + ' required file(s):\n' +
      errors.map((e) => '  - ' + e).join('\n') +
      '\n  copyBase: ' + copyBase + '\n  __dirname: ' + __dirname,
    )
  }

  console.log('  ✓ Utility files copied successfully')
}