import { GeneratorOptions } from '@prisma/generator-helper'
import * as fs from 'fs'
import * as path from 'path'

export async function copyFiles(options: GeneratorOptions): Promise<void> {
  const outputPath = options.generator.output?.value
  if (!outputPath) return

  const srcDir = path.join(__dirname, '..', '..', 'src', 'copy')

  const baseFiles = [
    'routeConfig.ts',
    'parseQueryParams.ts',
    'buildModelOpenApi.ts',
    'operationDefinitions.ts',
    'misc.ts',
  ]

  let allCopied = true

  console.log(`Copying utility files to: ${outputPath}`)

  for (const file of baseFiles) {
    const ok = await copyFile(srcDir, outputPath, file, { required: true })
    if (!ok) allCopied = false
  }

  const clientDir = path.join(outputPath, 'client')
  if (!fs.existsSync(clientDir)) {
    fs.mkdirSync(clientDir, { recursive: true })
  }

  const clientSrcDir = path.join(__dirname, '..', '..', 'src', 'client')
  const clientOk = await copyFile(
    clientSrcDir,
    clientDir,
    'encodeQueryParams.ts',
    {
      required: true,
      importRewrites: [{ from: '../copy/misc.js', to: '../misc.js' }],
    },
  )
  if (!clientOk) allCopied = false

  if (allCopied) {
    console.log(`✓ Utility files copied successfully`)
  } else {
    throw new Error(
      'One or more required utility files could not be copied. Generation aborted.',
    )
  }
}

interface CopyFileOptions {
  required?: boolean
  importRewrites?: Array<{ from: string; to: string }>
}

async function copyFile(
  srcDir: string,
  destDir: string,
  filename: string,
  options?: CopyFileOptions,
): Promise<boolean> {
  const srcPath = path.join(srcDir, filename)
  const destPath = path.join(destDir, filename)

  if (!fs.existsSync(srcPath)) {
    if (options?.required) {
      console.error(`✗ Required source file not found: ${srcPath}`)
      return false
    }
    console.warn(`⚠️  Source file not found: ${srcPath}`)
    return true
  }

  const destDirPath = path.dirname(destPath)
  if (!fs.existsSync(destDirPath)) {
    fs.mkdirSync(destDirPath, { recursive: true })
  }

  let content = fs.readFileSync(srcPath, 'utf-8')

  if (options?.importRewrites) {
    for (const rewrite of options.importRewrites) {
      content = content.replace(
        new RegExp(`from ['"]${escapeRegex(rewrite.from)}['"]`, 'g'),
        `from '${rewrite.to}'`,
      )
    }
  }

  const header = `/**
 * Auto-generated by prisma-generator-express
 * DO NOT EDIT MANUALLY
 */

`

  if (!content.startsWith('/**')) {
    content = header + content
  }

  fs.writeFileSync(destPath, content)
  console.log(`  ✓ Copied: ${filename}`)
  return true
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}