import { GeneratorOptions } from '@prisma/generator-helper'
import * as fs from 'fs'
import * as path from 'path'
import { Target } from '../constants.js'

const SHARED_FILES = [
  'parseQueryParams.ts',
  'buildModelOpenApi.ts',
  'operationDefinitions.ts',
  'misc.ts',
  'docsRenderer.ts',
]

const TARGET_FILES: Record<Target, string[]> = {
  express: ['routeConfig.ts'],
  fastify: ['routeConfig.ts'],
}

function resolveTemplateDir(subpath: string): string {
  const fromSibling = path.join(__dirname, '..', subpath)
  if (fs.existsSync(fromSibling)) return fromSibling

  const fromSrc = path.join(__dirname, '..', '..', 'src', subpath)
  if (fs.existsSync(fromSrc)) return fromSrc

  throw new Error(
    `Template directory "${subpath}" not found. Searched:\n  ${fromSibling}\n  ${fromSrc}\nEnsure template files are included in the published package.`,
  )
}

function getTargetSourceDir(copyBase: string, target: Target): string {
  if (target === 'express') return copyBase
  return path.join(copyBase, target)
}

interface CopyFileOptions {
  required?: boolean
  importRewrites?: Array<{ from: string; to: string }>
}

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

async function copyFile(
  srcDir: string,
  destDir: string,
  filename: string,
  options?: CopyFileOptions,
): Promise<boolean> {
  const srcPath = path.join(srcDir, filename)
  const destPath = path.join(destDir, filename)

  if (!fs.existsSync(srcPath)) {
    if (options?.required) {
      console.error(`✗ Required source file not found: ${srcPath}`)
      return false
    }
    console.warn(`⚠️  Source file not found: ${srcPath}`)
    return true
  }

  const destDirPath = path.dirname(destPath)
  if (!fs.existsSync(destDirPath)) {
    fs.mkdirSync(destDirPath, { recursive: true })
  }

  let content = fs.readFileSync(srcPath, 'utf-8')

  if (options?.importRewrites) {
    for (const rewrite of options.importRewrites) {
      content = content.replace(
        new RegExp(`from ['"]${escapeRegex(rewrite.from)}['"]`, 'g'),
        `from '${rewrite.to}'`,
      )
    }
  }

  const header = `/**
 * Auto-generated by prisma-generator-express
 * DO NOT EDIT MANUALLY
 */

`

  if (!content.startsWith('/**')) {
    content = header + content
  }

  fs.writeFileSync(destPath, content)
  console.log(`  ✓ Copied: ${filename}`)
  return true
}

export async function copyFiles(
  options: GeneratorOptions,
  target: Target,
): Promise<void> {
  const outputPath = options.generator.output?.value
  if (!outputPath) return

  const copyBase = resolveTemplateDir('copy')

  let allCopied = true

  console.log(`  Copying utility files to: ${outputPath} (target: ${target})`)

  for (const file of SHARED_FILES) {
    const ok = await copyFile(copyBase, outputPath, file, { required: true })
    if (!ok) allCopied = false
  }

  const targetSrcDir = getTargetSourceDir(copyBase, target)
  for (const file of TARGET_FILES[target]) {
    const ok = await copyFile(targetSrcDir, outputPath, file, {
      required: true,
    })
    if (!ok) allCopied = false
  }

  const clientDir = path.join(outputPath, 'client')
  if (!fs.existsSync(clientDir)) {
    fs.mkdirSync(clientDir, { recursive: true })
  }

  const clientSrcDir = resolveTemplateDir('client')
  const clientOk = await copyFile(
    clientSrcDir,
    clientDir,
    'encodeQueryParams.ts',
    {
      required: true,
      importRewrites: [{ from: '../copy/misc.js', to: '../misc.js' }],
    },
  )
  if (!clientOk) allCopied = false

  if (allCopied) {
    console.log(`  ✓ Utility files copied successfully`)
  } else {
    throw new Error(
      'One or more required utility files could not be copied. Generation aborted.',
    )
  }
}